# Generated by Django 5.2.8 on 2025-12-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compositores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('album', models.CharField()),
                ('ano', models.IntegerField()),
                ('duracao', models.TimeField()),
                ('artistas', models.ManyToManyField(related_name='musicas', through='newfy.Compositores', through_fields=('Musica', 'Artista'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compositores',
            name='Musica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newfy.musica'),
        ),
    ]
