# Generated by Django 5.2.9 on 2025-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
