# Generated by Django 5.2.9 on 2025-12-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfy', '0002_musica_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('nome', models.CharField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='musica',
            name='album',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='capa',
        ),
        migrations.AddField(
            model_name='musica',
            name='Album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newfy.album'),
        ),
    ]
