# Generated by Django 5.2.9 on 2025-12-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newfy', '0003_album_remove_musica_album_remove_musica_ano_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='Album',
            new_name='album',
        ),
    ]
